"""att usesrs

Revision ID: 2dba7b9654d6
Revises: e8433bf27858
Create Date: 2025-08-28 00:00:30.787631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dba7b9654d6'
down_revision = 'e8433bf27858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['vendendor_id'], ['id'])

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('setor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('setor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendendor_id')

    # ### end Alembic commands ###
