"""ATT PRODUTOS

Revision ID: 4244984a0024
Revises: d31d73eb6ffb
Create Date: 2025-08-17 17:27:02.321660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4244984a0024'
down_revision = 'd31d73eb6ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_pedidos', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_pedidos', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
