"""ATT pedidos

Revision ID: 4b90b52e29c4
Revises: a94098e1a0cb
Create Date: 2025-08-16 22:07:45.934033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b90b52e29c4'
down_revision = 'a94098e1a0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('endereco_motorista_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('endereco_motorista_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
