"""ATT pedidos/motorista

Revision ID: 6e416748921a
Revises: bdb727fdfb5a
Create Date: 2025-08-16 22:21:50.146604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e416748921a'
down_revision = 'bdb727fdfb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorista_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['motorista_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('motorista_id')

    # ### end Alembic commands ###
