"""ATT pedidos

Revision ID: 9bf559dbcb1b
Revises: 4b90b52e29c4
Create Date: 2025-08-16 22:12:50.946637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf559dbcb1b'
down_revision = '4b90b52e29c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_externo', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['cod_externo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cod_externo')

    # ### end Alembic commands ###
