"""ATT Clientes

Revision ID: a94098e1a0cb
Revises: e0e3a5e85d16
Create Date: 2025-08-16 20:22:47.001324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94098e1a0cb'
down_revision = 'e0e3a5e85d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_externo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo_externo'])
        batch_op.create_foreign_key(None, 'users', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('codigo_externo')

    # ### end Alembic commands ###
