"""ATT PRODUTOS

Revision ID: d31d73eb6ffb
Revises: 6e416748921a
Create Date: 2025-08-17 17:15:00.709555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd31d73eb6ffb'
down_revision = '6e416748921a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo'])
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tipo')
        batch_op.drop_column('categoria')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
