"""ATTVEICULOS

Revision ID: db1d930cd085
Revises: 4244984a0024
Create Date: 2025-08-21 01:02:12.869304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1d930cd085'
down_revision = '4244984a0024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obs', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('obs')

    # ### end Alembic commands ###
