"""ADD BAIRRO, CIDADE EM ENDEREÇOS

Revision ID: e8433bf27858
Revises: 
Create Date: 2025-08-24 20:28:02.076226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8433bf27858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos_adm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=False))

    with op.batch_alter_table('enderecos_motoristas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos_motoristas', schema=None) as batch_op:
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')

    with op.batch_alter_table('enderecos_adm', schema=None) as batch_op:
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
